name: 🔬 Deploy test version [auto]

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README*.md"
      - ".gitignore"
      - ".github/**"
      - ".vscode/**"
      - "Makefile"
      - "examples/**"
      - ".bumpversion.cfg"
      - "pyproject.toml"

concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
    
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   needs: pre-commit
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #     - run: pip install -r requirements-test.txt -r requirements.txt
  #     - run: python -m pytest tests/

  build-and-publish-package:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    # needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install build-dependencies
        run: pip install -r requirements-build.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump up package version
        run: |
          bump2version patch --verbose

      - name: Add and push changes
        run: |
          git add .
          git push
        env:
          GIT_TOKEN: ${{ secrets.GH_PAT }}

      - name: Build package and publish
        working-directory: src
        run: |
          python -m build
          python -m twine upload \
          --repository testpypi \
          --username '__token__' \
          --password '${{ secrets.TEST_PYPI_TOKEN }}' \
          dist/* \
          --verbose
