name: 🔬 Deploy test version [auto]

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - "README*.md"
      - ".gitignore"
      - ".github/**"
      - ".vscode/**"
      - "Makefile"
      - "examples/**"
      - ".bumpversion.cfg"
      - "pyproject.toml"

concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install build-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-build.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump up package version
        run: |
          bump2version patch --verbose

      - name: Add and push changes
        run: |
          git add .
          git push
        env:
          GIT_TOKEN: ${{ secrets.GH_PAT }}

      - name: Build package and publish
        working-directory: src
        run: |
          python -m build
          python -m twine upload \
          --repository testpypi \
          --username '__token__' \
          --password '${{ secrets.TEST_PYPI_TOKEN }}' \
          dist/* \
          --verbose
